convert_R_S3_R_S4.pl -R_source as_BioData.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/as_BioData.R
convert_R_S3_R_S4.pl -R_source cellexalvrClass.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/cellexalvrClass.R
convert_R_S3_R_S4.pl -R_source cellexalvrExportFunctions.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/cellexalvrExportFunctions.R
convert_R_S3_R_S4.pl -R_source cellexalvrFunctions.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/cellexalvrFunctions.R
convert_R_S3_R_S4.pl -R_source cellexalvrNetworkFunctions.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/cellexalvrNetworkFunctions.R
convert_R_S3_R_S4.pl -R_source cellexalvr.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/cellexalvr.R
convert_R_S3_R_S4.pl -R_source data.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/data.R
convert_R_S3_R_S4.pl -R_source defineGOIs.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/defineGOIs.R
convert_R_S3_R_S4.pl -R_source exportUserGroups4vr.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/exportUserGroups4vr.R
convert_R_S3_R_S4.pl -R_source groupingInfo.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/groupingInfo.R
convert_R_S3_R_S4.pl -R_source lockedSave.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/lockedSave.R
convert_R_S3_R_S4.pl -R_source logging.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/logging.R
convert_R_S3_R_S4.pl -R_source onlyGOIs.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/onlyGOIs.R
convert_R_S3_R_S4.pl -R_source oscilliatingGenes.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/oscilliatingGenes.R
convert_R_S3_R_S4.pl -R_source reduceTo.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/reduceTo.R
convert_R_S3_R_S4.pl -R_source renew.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/renew.R
convert_R_S3_R_S4.pl -R_source reorder.obj.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/reorder.obj.R
convert_R_S3_R_S4.pl -R_source seuratExtensions.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/seuratExtensions.R
convert_R_S3_R_S4.pl -R_source useInbuiltGOIlists.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/useInbuiltGOIlists.R
convert_R_S3_R_S4.pl -R_source userGrouping.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/userGrouping.R
convert_R_S3_R_S4.pl -R_source vrPrepare.R -className cellexalvr -outfile ~/tmp/cellexalvr/R/vrPrepare.R
