# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

toColNums <- function(data) {
    .Call(`_cellexalvrR_toColNums`, data)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_cellexalvrR_RcppExport_registerCCallable', PACKAGE = 'cellexalvrR')
})
