# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logFC <- function(A, B) {
    .Call(`_cellexalvrR_logFC`, A, B)
}

StatTest <- function(X, interest, backgound, logFCcut = 1.0, display_progress = TRUE) {
    .Call(`_cellexalvrR_StatTest`, X, interest, backgound, logFCcut, display_progress)
}

toColNums <- function(data) {
    .Call(`_cellexalvrR_toColNums`, data)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_cellexalvrR_RcppExport_registerCCallable', PACKAGE = 'cellexalvrR')
})
